addons:
  apt:
    packages:
    - libdbus-1-dev
    - libx11-dev
    - libxrandr-dev
    - libxinerama-dev
    - libxss-dev
    - libxdg-basedir-dev
    - libglib2.0-dev
    - libpango1.0-dev
    - libcairo2-dev
    - libnotify-dev
    - libgtk-3-dev
dist: trusty
sudo: false
language: c
script: CFLAGS=-Werror make && make test
compiler:
    - gcc
    - clang
notifications:
    irc:
        channels:
            - "chat.freenode.net#dunst"
        on_success: change
        on_failure: always
